# Generated by Django 3.1.1 on 2024-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gold_member',
            field=models.BooleanField(default=False),
        ),
    ]
