# Generated by Django 3.1.1 on 2024-09-12 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery', '0004_grocerystore_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerystore',
            name='working_hours',
            field=models.CharField(default='9 AM - 9 PM', max_length=100),
        ),
        migrations.CreateModel(
            name='GroceryReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grocery_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grocery.grocerystore')),
            ],
        ),
    ]
