# Generated by Django 3.1.1 on 2024-09-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_auto_20240912_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
