# Generated by Django 3.1.1 on 2024-09-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
